### ISSUE TITLE
INVALID_ARGUMENT: Invalid resource field value in the request

### ISSUE THREAD

**Issue by jasonsilberman** [googleapis/nodejs-domains#97]
I am trying to use the `searchDomains` method on DomainsClient but am getting the following error:

```
Error: 3 INVALID_ARGUMENT: Invalid resource field value in the request.
    at Object.callErrorFromStatus (~/project/node_modules/@google-cloud/domains/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (~/project/node_modules/@google-cloud/domains/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
    at Object.onReceiveStatus (~/project/node_modules/@google-cloud/domains/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (~/project/node_modules/@google-cloud/domains/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at ~/project/node_modules/@google-cloud/domains/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

#### Environment details

  - OS: macOS
  - Node.js version: v14.18.2
  - npm version: 7.20.1
  - `@google-cloud/domains` version: 1.2.0

#### Steps to reproduce

  1. Initiate client
  2. Call `client.searchDomains`

```js
const searchResult = await client.searchDomains({
   query: domain,
});

console.log(searchResult);
```

I have tried the `listRegistrations` API and that is working fine so I know that the client is properly authenticated and initialized. I am trying to use this API to search for and then register domains.

I am also receiving the same error when I use the `client.retrieveRegisterParameters()` method.

Could you please point me in the right direction for how I can fix this error? I am really quite confused by what is going on.

Thanks!

**Comment by sofisl** [comment]
Closing due to inactivity.
